"""Phase 8 models and RAG fields

Revision ID: 3939b4efed4b
Revises: 414c1ee4b971
Create Date: 2026-06-15 12:15:23.683573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3939b4efed4b'
down_revision: Union[str, Sequence[str], None] = '414c1ee4b971'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('workforce_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workforce_plans_id'), 'workforce_plans', ['id'], unique=False)
    op.create_table('headcount_budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('designation_id', sa.Integer(), nullable=False),
    sa.Column('current_count', sa.Integer(), nullable=False),
    sa.Column('planned_additions', sa.Integer(), nullable=False),
    sa.Column('budget_amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['designation_id'], ['designations.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['workforce_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_headcount_budgets_id'), 'headcount_budgets', ['id'], unique=False)
    op.create_table('skill_gap_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('required_skill', sa.String(length=100), nullable=False),
    sa.Column('current_proficiency', sa.String(length=50), nullable=True),
    sa.Column('target_proficiency', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['workforce_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_gap_items_id'), 'skill_gap_items', ['id'], unique=False)
    op.add_column('hr_policies', sa.Column('pdf_file_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hr_policies', 'pdf_file_path')
    op.drop_index(op.f('ix_skill_gap_items_id'), table_name='skill_gap_items')
    op.drop_table('skill_gap_items')
    op.drop_index(op.f('ix_headcount_budgets_id'), table_name='headcount_budgets')
    op.drop_table('headcount_budgets')
    op.drop_index(op.f('ix_workforce_plans_id'), table_name='workforce_plans')
    op.drop_table('workforce_plans')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
