"""phase_2_recruitment_onboarding

Revision ID: 414c1ee4b971
Revises: 1c2f3a4b5d6e
Create Date: 2026-06-11 15:58:14.106880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '414c1ee4b971'
down_revision: Union[str, Sequence[str], None] = '1c2f3a4b5d6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_acknowledgments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['hr_policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_acknowledgments_employee_id'), 'policy_acknowledgments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_policy_acknowledgments_id'), 'policy_acknowledgments', ['id'], unique=False)
    op.create_table('candidate_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_status_history_candidate_id'), 'candidate_status_history', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_status_history_id'), 'candidate_status_history', ['id'], unique=False)
    op.create_table('interview_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('interviewer_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['interviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_feedback_candidate_id'), 'interview_feedback', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_interview_feedback_id'), 'interview_feedback', ['id'], unique=False)
    op.create_table('onboarding_asset_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['onboarding_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_asset_requests_case_id'), 'onboarding_asset_requests', ['case_id'], unique=False)
    op.create_index(op.f('ix_onboarding_asset_requests_id'), 'onboarding_asset_requests', ['id'], unique=False)
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('approved_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approval_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_foreign_key('fk_jobs_approved_by_id', 'users', ['approved_by_id'], ['id'])

    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata_json', sa.JSON(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_users_employment_type_id', 'employment_types', ['employment_type_id'], ['id'])
        batch_op.create_foreign_key('fk_users_work_location_id', 'work_locations', ['work_location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_work_location_id', type_='foreignkey')
        batch_op.drop_constraint('fk_users_employment_type_id', type_='foreignkey')

    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_column('metadata_json')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_jobs_approved_by_id', type_='foreignkey')
        batch_op.drop_column('approval_date')
        batch_op.drop_column('approved_by_id')
        batch_op.drop_column('is_approved')
    op.drop_index(op.f('ix_onboarding_asset_requests_id'), table_name='onboarding_asset_requests')
    op.drop_index(op.f('ix_onboarding_asset_requests_case_id'), table_name='onboarding_asset_requests')
    op.drop_table('onboarding_asset_requests')
    op.drop_index(op.f('ix_interview_feedback_id'), table_name='interview_feedback')
    op.drop_index(op.f('ix_interview_feedback_candidate_id'), table_name='interview_feedback')
    op.drop_table('interview_feedback')
    op.drop_index(op.f('ix_candidate_status_history_id'), table_name='candidate_status_history')
    op.drop_index(op.f('ix_candidate_status_history_candidate_id'), table_name='candidate_status_history')
    op.drop_table('candidate_status_history')
    op.drop_index(op.f('ix_policy_acknowledgments_id'), table_name='policy_acknowledgments')
    op.drop_index(op.f('ix_policy_acknowledgments_employee_id'), table_name='policy_acknowledgments')
    op.drop_table('policy_acknowledgments')
    # ### end Alembic commands ###
